### ISSUE TITLE
Links to plans should open new tab

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cwcb-viz-co-watershed-plans#1]
Opening documents can take awhile and then have to go back to the application, losing the document window and also the state of the mapping application.  The links should open in a new tab.

**Comment by smalers** [comment]
Or, maybe under Documentation explain that people should right-click and use "Open in new tab".  The problem is ... how does it behave on mobile devices?

**Comment by Korysam15** [comment]
Fixed this issue. Every link on the webpage including the links for each water plan will now open up in a new tab. Closing issue.
