### ISSUE TITLE
Typo in popup

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cwcb-viz-co-watershed-plans#2]
Popup says "Infromation".  Need to fix.

**Comment by smalers** [comment]
Also, change "Basin Name" to "Basin HUC8 Name" so the label is consistent with suggestions for plan data.

**Comment by Korysam15** [comment]
Fixed issue. Added the proper spelling of 'information' and fixed the popup to display 'Basin HUC8 Name' instead of 'Basin Name'. Closing issue.
