### ISSUE TITLE
Change documentation text

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cwcb-viz-co-watershed-plans#3]
The documentation tab has "Information about the plan will be shown in a popup. Click on the link to the the watershed plan to view the plan document.".

This should be changed to:  "Information about the basin will be shown in a popup and a list of available plans will be shown on the right. Click on the link to the a watershed plan to view the plan document in a new tab."

**Comment by Korysam15** [comment]
Fixed error. Also corrected minor grammar error. When saying 'Click on the link to the a watershed plan' I changed this to 'Click on the link to a watershed plan'. Closing issue.
