### ISSUE TITLE
Some plan documents are not found

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cwcb-viz-co-watershed-plans#4]
Clicking on plan document links returns no document in some cases.   Also, the links are shown with URL encoding (%20), etc.  The visible link text to users should not include encoding, but used the URL encoding in the hidden link if necessary.

Need to automate checking all the document URLs and give feedback to the CWCB.  For example, can use TSTool to read in the csv as a table, then use the For() and EndFor() commands to loop and inside the loop use WebGet().  An error should be shown for each not found document.  Or, write a short script (Cygwin sh for example) that uses curl to retrieve each document and if not found generate an error.  The results of the check can be provided to the CWCB so that the maintainer of the dataset can track down the documents and the table updated.  The script can be saved in a folder in the repository so that it can be run when data are updated, for example a "data-check" folder under the main folder (not under site).

**Comment by smalers** [comment]
I found that the CSV file format was messed up.  The Save As from QGIS resulted in strange formatting in the CSV, which I had to manually fix.  I think I saved from the attribute table in QGIS the first time. 
 There were apparently embedded line breaks, quotes, etc.

Updated Watershed_Plans.csv is in Dropbox.  Also there is the new TSTool command file CheckLinkedDocumentExistence.TSTool, but this requires TSTool 12.04.00, which fixes a few minor bugs to deal withe the CSV file in a robust way.  The command file has some issues but generally did detect most issues.

Hopefully using the new CSV file will improve the visualization. 

Steve emailed the CWCB the check file as an FYI (attached).
[Watershed_Plans_Check.xlsx](https://github.com/OpenWaterFoundation/cwcb-viz-co-watershed-plans/files/1082423/Watershed_Plans_Check.xlsx)

**Comment by Korysam15** [comment]
I went ahead and added the updated Watershed_Plans.csv to the repository. NOTE: There are still links that can't be found! This should be fixed once the CWCB sends back a .csv with the proper (most up-to-date) links. I also went ahead and added the TSTool command file. I will make a note in the README.md explaining what it is for and to use it with TSTool 12.04.00.

**Comment by smalers** [comment]
I synced to Amazon S3. Now the map does not display.  Need Kory to check it out.  It worked OK when I pulled the changes from the master branch and ran with a local Python server.
