### ISSUE TITLE
Change Data tab information

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cwcb-viz-co-watershed-plans#7]
The Data tab information should be updated as follows:
 Add introduction:

Data for the visualization include the HUC8 basin boundaries and a comma-separated-value (CSV) file with the plan data.  Each HUC8 basin can have zero or more plans.  The original basin file as a GeoJSON file was 24 MB and was pruned by removing points.  The Watershed_Plans.csv file "SubBasin" field contains the HUC8 identifier, which matches the Watershed_Plans_Pruned.geojson "HUC8" property.  Properties shown in the visualization are taken from both files.

Watershed_Plans.csv
Watershed_Plans.geojson
Watershed_Plans_Pruned.geojson

====
Also, the files in the repo don't match the pruned filename.  The Watershed_Plans_Simpified0006.geojson file should be renamed to Watershed_Plans_Pruned.geojson.  There is no need to include the tsv in the download.

**Comment by Korysam15** [comment]
Fixed issued. Added specified text to data tab and renamed file in data-files to Watershed_Plans_Pruned.geojson. Closing issue.
