### ISSUE TITLE
HUC8 property in the geojson should be an integer, not floating point

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cwcb-viz-co-watershed-plans#8]
The HUC8 property in the geojson file should be an integer but appears to have been written as a float.  It appears that this was also an issue in the original 24MB basin file.  I think a simple search and replace will work where ".0," is replaced with ",", but be careful to not change other numbers in the file in a destructive way.  Then the code should be more appropriate also.

**Comment by Korysam15** [comment]
Fixed this in the Watershed_Plans_Pruned.geojson. Will correct the original file as well. Closing issue.
