### ISSUE TITLE
Improve wateshed plan information that is listed

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cwcb-viz-co-watershed-plans#9]
The watershed plan information that is shown on the right should include a little bit of information about the HUC8 basin and then output the information from CSV and geojson as follows.  The information in square brackets is for the programmer and should not be displayed.  Given that we don't control this information, the best we can do right now is display.

====

Basin HUC8 ID:  same as popup
Basin HUC8 Name:  same as popup
Plans:  same as popup

[Then for each plan, listed with newest year first]:

Year: [csv Year or N/A]
Plan Title: [csv Plan_Title]
Sub-basin:  [csv SubBasin]
River/stream: [csv River_Stream]
Basin(s):  [csv Basin]
Organization:  [csv Organization]
Link to Plan:  [csv Link]

**Comment by Korysam15** [comment]
Fixed issue. Added specified content to right hand information display. Closing issue.
